Update patch set 1
Patch Set 1:

> sdninterfaceapp-verify-beryllium/65/ : FAILURE

Some bundle version fixing needs to be done before this passes:

java.lang.IllegalStateException: Can't install feature odl-sdni-api/0.7.0-SNAPSHOT: 	
Could not start bundle mvn:org.opendaylight.sdninterfaceapp/sdninterfaceapp-api/0.7.0-SNAPSHOT in feature(s) odl-sdni-api-0.7.0-SNAPSHOT: Unresolved constraint in bundle org.opendaylight.sdninterfaceapp.api [85]: Unable to resolve 85.0: missing requirement [85.0] osgi.wiring.package; (&(osgi.wiring.package=com.google.common.collect)(version>=18.0.0)(!(version>=19.0.0)))

Patch-set: 1
Reviewer: Gerrit User 2046 <2046@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Verified=0